```yaml id="vknzy0"
name: alarm

on:
  repository_dispatch:
    types: [play_alarm]

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: update state

        run: |

          echo "play $(date +%s)" > state.txt

      - name: commit

        run: |

          git config user.name "github-actions"

          git config user.email "actions@github.com"

          git add state.txt

          git commit -m "alarm"

          git push
```
